### ISSUE TITLE
Add ability to specify Payment Plan

### ISSUE THREAD

**Issue by jzalewskiADVR** [ChrisKronbergADVR/AndoverAutomation#3]
**Is your feature request related to a problem? Please describe.**
We are looking to quickly create some policies for Erica's SmartComm testing. One of the specifications of her test cases is to use all of the different pay plans throughout her tests.

**Describe the solution you'd like**
An additional dropdown field on the Andover Automation UI for Payment Plan, and associated logic to select the chosen value. As for the pay plans that require an additional field in ACX like ACH payment details, or due day of month, default test data works fine.

**Describe alternatives you've considered**
We've considered alternate tools, but after discussion with the team, we are limited with the test data generator from parrot team (does not currently have user login option) and the automated selenium code (we'd have to write and configure many tests and have had issues configuring environments other than QA). 

**Additional context**
The payment plan selection involves the options on the Billing tab when creating a policy, for example: 
![image](https://github.com/ChrisKronbergADVR/AndoverAutomation/assets/155775627/6de20002-c8c2-4b24-b64e-a0e491b9f0ec)

**Comment by ChrisKronbergADVR** [comment]
Some states have different values for billing options so I will have to revisit this and check every states billing option values

**Comment by ChrisKronbergADVR** [comment]
This should be fixed now. If you run into issues please let me know so I can fix them.
