### ISSUE TITLE
Add PUMB and CUMB/CEL options to LOB dropdown

### ISSUE THREAD

**Issue by jzalewskiADVR** [ChrisKronbergADVR/AndoverAutomation#5]
**Is your feature request related to a problem? Please describe.**
We are looking to quickly create some policies for Erica's SmartComm testing. One of the specifications of her test cases is to utilize all the lines of business, including umbrella policies.

**Describe the solution you'd like**
Add additional options for Umbrella policies on the Andover Automation UI in the existing Line of Business dropdown, and associated logic to select the chosen value and execute the creation of the policy. Noting that CUMB and CEL are essentially created in the same manner and I believe eventually most states are moving from CUMB to CEL.

**Describe alternatives you've considered**
We've considered alternate tools, but after discussion with the team, we are limited with the test data generator from parrot team (does not currently have user login option) and the automated selenium code (we'd have to write and configure many tests and have had issues configuring environments other than QA).

**Additional context**
If steps are needed on how to create PUMB or CEL/CUMB policies, I'll be happy to provide. Thanks!

**Comment by ChrisKronbergADVR** [comment]
This should be resolved. If you find any issues please let me know so I can fix them
